### PR TITLE
Fixed "watch on YT" button on invidious

### PR DESCRIPTION
**Pull request by hutattedonmyarm**
The "Watch on youtube" button would redirect back to invidious. I've added a check to prevent this

### CODE REVIEW

**Comment by doronbehar** [comment]
Hey, thanks for the PR. I guess this is sort of solves the issues presented in #1. I'd be willing to merge this but I'm not sure as for the implementation. First of all I've tested the "Watch on Youtube" button on invidio.us with your PR checked out and I was redirected back to invidio.us afterwards - did you forgot to push some commits?

If you are willing to contribute, first of all please revert the change to the extension's id in the manifest :) I know you probably changed it for your own usage..

Besides that, I'd really prefer if the extension could just be disabled with a button, as discussed with @ghost back in #1. This also has the advantage that if any other issues arise by users when browsing the web and the extension's behavior is problematic for them, it could be disabled temporarily so.

**Comment by hutattedonmyarm** [comment]
Hi, I've taken another look at the issue. You don't happen to have the Multi Account Containers extension installed? I've found that on the first click to "Watch on YT" the MAC extension redirects to a Google container, and therefore the origin url is not incidious anymore, but `moz-extension://<id>/`. Now the invidious tab is open in the Google container and subsequent clicks on the button work. I'm not entirely sure how to handle that though.

Having a manual enable/disable button would work, although myself I'd prefer it to work automatically.  
I guess both might be an option? Add a checkbox to the extension settings which enables/disables the current automatic behavior and add a toolbar button to manually en-/disable the redirect

**Comment by doronbehar** [comment]
> You don't happen to have the Multi Account Containers extension installed?

I do.

> Having a manual enable/disable button would work, although myself I'd prefer it to work automatically.
I guess both might be an option? Add a checkbox to the extension settings which enables/disables the current automatic behavior and add a toolbar button to manually en-/disable the redirect

As I said I'd prefer to keep it simple - having a single toggle button should be enough.

**Comment by SeriousM** [comment]
Hi! I would love to have the "Watch on YT" button to work. Will you enable a tooltip button to allow it?

**Comment by doronbehar** [comment]
So @hutattedonmyarm, do you have any idea how to handle the case of Google Container addon users? Although I said I'd prefer to have a simple on-off button instead, I'd consider merging this if the "Watch on YoutTube" link in Invidio.us would work for Google Container addon users like me.

**Comment by hutattedonmyarm** [comment]
@doronbehar I fiddled around with the API a bit. So the initial problem with the container addon is, that opens the YouTube link (coming from Invidious) in a new container, which screws with the origin of the webrequest, so I can't detect that the request initiated from Invidious and should be forwarded to YouTube.

I found the following solution: I can detect that the request comes from the extension (I could add either a couple of the container extensions to a list or just check for *any* extension as the origin of the request). I can then check which tab which opened the current one and compare URLs and container info. If all of the following are true:

* The current target is a YouTube URL
* The origin is an extension
* The tab which opened the current one is an Invidious tab with the same Video/Playlist/etc ID as the current target
* The opener tab lives in a different container than the current one

Then I can be reasonably sure that the user clicked the "Watch on Youtube" button and got redirected by a container extension and forward to Youtube.

I can build that in and even add a toolbar button to manually enable/disable the extension. that would require an icon though, which I could make but it will be pretty barebones

**Comment by hutattedonmyarm** [comment]
@SeriousM I have created a fork of the extension with that enabled [and uploaded it to the extension gallery](https://addons.mozilla.org/en-US/firefox/addon/invidious-redirect-2/). Keep in mind that it doesn't play completely nice with Multi Account Containers or Google Container for now (that is work in progress though) and it doesn't have a tooltip button to toggle that, but will do so automatically

**Comment by doronbehar** [comment]
Thanks for investigating this @hutattedonmyarm . Please let me know when you'll make more progress.

I appreciate your effort in adding your fork to the extensions gallery but I'd honestly prefer if it wouldn't exist and your changes would have been merged somehow. Perhaps we can add a Boolean option to the settings which will enable or disable this new behavior? Along with mentioning there that it setting this option to `true` doesn't play well if you have a Container addon?

Please let me know what do you think.

**Comment by hutattedonmyarm** [comment]
@doronbehar so a setting to en-/disable the automatic forward plus a toolbarbutton to manually en-/disable all forwarding (basically en-/disabling the extension)?

**Comment by doronbehar** [comment]
> so a setting to en-/disable the automatic forward plus a toolbarbutton to manually en-/disable all forwarding (basically en-/disabling the extension)?

Putting all of these new features together would be awesome :) You don't have to do it all in one PR though, whatever you wish.

**Comment by hutattedonmyarm** [comment]
So the auto-redirect is fixed and works with container addons. Toolbarbutton is as good as done, I hope I'll get around to make an icon during the weekend

**Comment by doronbehar** [comment]
Thanks a lot for your efforts @hutattedonmyarm . I've checked out your changes and tested them with using the addons:debugging . I don't use the multi account containers addon, I use the [Google container addon](https://addons.mozilla.org/en-US/firefox/addon/google-container) and I get redirected to invidio.us back when I hit the "Watch on YouTube" link. Did you test it with another container related addon?

I really get the sense that this feature could never become stable so thinking more about this brings me to conclude that I'd really prefer not having any workaround other then a indicating On/Off button, perhaps along with a keyboard shortcut.

I'll update the description of the extension to mention this issue and the fact that it's hard to impossible to workaround it, at least for Users with the Google container addon.

**Comment by doronbehar** [comment]
Hi again,

I've found out recently about an addon called [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector) which is just a general purpose addon with the same purpose as this one. It has builtin toolbar with a toggle button.

I'm using it now and so I don't see a point in maintaining this. Closing, feel free to fork this and publish yours.

**Pull request closed without merging**
